---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
pipelines:
  noop:
    stages:
    - noop: {}
  500s-successful-pipeline:
    stages:
    - 500s-successful-stage: {}
stages:
  noop:
    workflows:
    - noop: {}
  500s-successful-stage:
    workflows:
    - 500s-successful-workflow: {}
workflows:
  500s-successful-workflow:
    steps:
    - script@1.2:
        inputs:
        - content: |-
            #!/bin/bash

            echo "First"

            for i in {1..1000}
            do
                echo "Time passed: $i tizedseconds"
                sleep .1
            done

            echo "First script success!"
    - script:
        title: Second script
        inputs:
        - content: |-
            #!/bin/bash

            echo "Second"

            for i in {1..100}
            do
                echo "Time passed: $i seconds"
                sleep 1
            done

            echo "Second script success!"
    - script:
        title: Third script
        inputs:
        - content: |-
            #!/bin/bash

            echo "Third"

            for i in {1..1000}
            do
                echo "Time passed: $i tizedseconds"
                sleep .1
            done

            echo "Third script success!"
    - script:
        title: Fourth script
        inputs:
        - content: |-
            #!/bin/bash

            echo "Fourth"

            for i in {1..100}
            do
                echo "Time passed: $i seconds"
                sleep 1
            done

            echo "Fourth script success!"
    - script:
        title: Fifth script
        inputs:
        - content: |-
            #!/bin/bash

            echo "Fifth"

            for i in {1..1000}
            do
                echo "Time passed: $i tizedseconds"
                sleep .1
            done

            echo "Fifth script success!"
  noop:
    meta:
      bitrise.io:
        machine_type_id: standard
  sleep:
    steps:
    - script@1:
        inputs:
        - content: |-
            set -ex

            sleep 12000000
    meta:
      bitrise.io:
        stack: osx-xcode-14.3.x-ventura
        machine_type_id: standard
